# Generated by Django 4.0.4 on 2022-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='mobile_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='mobile code'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tag'),
        ),
    ]
